language: go

go:
  - "1.11.x"

env:
  - GO111MODULE=on

service:
  - docker

install:
  - docker-compose build

before_script:
  - docker-compose up -d db

script:
  - docker-compose run server sh -c "go test -v socialservice/server"
