version: "3"

services:
  server:
    build: ./
    ports:
      - "5100:5100"
    depends_on: 
      - db

  db:
    image: "mysql:5.7"
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: nphw3
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"