package socialserviceserver

import (
	"database/sql"
	"log"
	"os"
	"socialservice/client"
	"sort"
	"strings"
	"testing"
	"time"

	_ "github.com/go-sql-driver/mysql"
)

type testcase struct {
	testName string
	testlist []string
	wantlist [][]string
}

var db *sql.DB

func setup() {
	var err error
	db, err = sql.Open("mysql", "admin:test@tcp(db)/nphw3")
	if err != nil {
		log.Fatalln("Could not open database: ", err)
	}
	for retryTime := 0; db.Ping() != nil; retryTime++ {
		if retryTime >= 10 {
			log.Fatalln("Could not connet to database")
		}
		time.Sleep(time.Duration(10) * time.Second)
	}
	err = SetAddr("127.0.0.1", "2222")
	if err != nil {
		log.Fatalln("Could not set address: ", err)
	}
	err = CreateTables(db)
	if err != nil {
		log.Fatalln("Could not create tables: ", err)
	}
	go Run(db)
	time.Sleep(time.Second)
}

func teardown() {
	db.Close()
}

func TestMain(m *testing.M) {
	setup()
	retCode := m.Run()
	teardown()
	os.Exit(retCode)
}

func beforeTest(t testing.TB) {}

func afterTest(t testing.TB) {
	err := TruncateTables(db)
	if err != nil {
		t.Error("Could not truncate tables: ", err)
	}
}

func doTest(t *testing.T, testlist []testcase) {
	for _, tc := range testlist {
		t.Run(tc.testName, func(t *testing.T) {
			// Act
			client, err := client.NewTCPClient("127.0.0.1", "2222")
			if err != nil {
				t.Error("Could not create client: ", err)
			}

			// Assert
			for i := range tc.wantlist {
				response := client.Execute(tc.testlist[i])
				out := strings.Split(response, "\n")
				want := tc.wantlist[i]
				sort.Strings(out)
				sort.Strings(want)
				for j := range want {
					if out[j] != want[j] {
						t.Errorf("response did match expected output: %d\nExpect:%s\nReal:%s\n", i, want[j], out[j])
					}
				}
			}
		})
	}
}

func TestHW2(t *testing.T) {
	// Arrange
	testlist := []testcase{
		{
			"Test1",
			[]string{
				"register t1_user1_test 111",
				"register t1_user2_test 222",
				"register t1_user2_test 222",
				"register t1_user3_test 333",
				"login",
				"login t1_user1_test 111",
				"login t1_user1_test 123",
				"login 12e t1_test",
				"login t1_user2_test 222",
				"login t1_user3_test 333",
				"logout t1_user4_test",
				"logout t1_user1_test",
				"delete t1_user1_test",
				"login t1_user1_test 111",
				"invite t1_user1_test t1_user2_test",
				"invite t1_user1_test t1_user3_test",
				"list-invite t1_user2_test",
				"list-invite t1_user3_test",
				"accept-invite t1_user2_test t1_user1_test",
				"accept-invite t1_user2_test t1_user3_test",
				"accept-invite t1_user3_test t1_user1_test",
				"list-friend t1_user1_test",
				"list-friend t1_user4_test",
				"post t1_user1_test hello",
				"receive-post t1_user2_test",
				"delete t1_user1_test",
				"delete t1_user2_test",
				"delete t1_user3_test",
				"delete t1_user4_test",
			},
			[][]string{
				{"Success!"},
				{"Success!"},
				{"t1_user2_test is already used"},
				{"Success!"},
				{"Usage: login <id> <password>"},
				{"Success!"},
				{"No such user or password error"},
				{"No such user or password error"},
				{"Success!"},
				{"Success!"},
				{"Not login yet"},
				{"Bye!"},
				{"Not login yet"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"t1_user1_test"},
				{"t1_user1_test"},
				{"Success!"},
				{"t1_user3_test did not invite you"},
				{"Success!"},
				{"t1_user2_test", "t1_user3_test"},
				{"Not login yet"},
				{"Success!"},
				{"t1_user1_test: hello"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Not login yet"},
			},
		},
		{
			"Test2",
			[]string{
				"register t2_user1_test",
				"register t2_user1_test zzz zzz",
				"register",
				"login t2_user1_test 111",
				"login t2_user2_test 222",
				"delete t2_user3_test",
				"login t2_user3_test 333",
				"accept-invite t2_user1_test t2_user2_test",
				"invite t2_user1_test t2_user2_test",
				"invite t2_user1_test t2_user1_test",
				"invite t2_user1_test t2_user4_test",
				"register t2_user4_test 444",
				"login t2_user4_test 444",
				"invite t2_user1_test t2_user4_test",
				"list-invite t2_user4_test",
				"accept-invite t2_user4_test t2_user1_test",
				"list-friend t2_user1_test",
				"delete t2_user1_test",
				"delete t2_user2_test",
				"delete t2_user3_test",
				"delete t2_user4_test",
			},
			[][]string{
				{"Usage: register <id> <password>"},
				{"Usage: register <id> <password>"},
				{"Usage: register <id> <password>"},
				{"No such user or password error"},
				{"No such user or password error"},
				{"Not login yet"},
				{"No such user or password error"},
				{"Not login yet"},
				{"Not login yet"},
				{"Not login yet"},
				{"Not login yet"},
				{"Success!"},
				{"Success!"},
				{"Not login yet"},
				{"No invitations"},
				{"t2_user1_test did not invite you"},
				{"Not login yet"},
				{"Not login yet"},
				{"Not login yet"},
				{"Not login yet"},
				{"Success!"},
			},
		},
		{
			"Test3",
			[]string{
				"register t3_userA_test 111",
				"register t3_userB_test 222",
				"register t3_userC_test 333",
				"login t3_userA_test 123",
				"login t3_userA_test 111",
				"login t3_userD_test 444",
				"delete t3_userB_test",
				"login t3_userB_test 222",
				"login t3_userC_test 333",
				"invite t3_userA_test t3_userB_test",
				"invite t3_userA_test t3_userA_test",
				"invite t3_userA_test t3_userB_test",
				"invite t3_userB_test t3_userA_test",
				"invite t3_userA_test t3_userD_test",
				"accept-invite t3_userA_test t3_userB_test",
				"accept-invite t3_userB_test t3_userA_test",
				"invite t3_userA_test t3_userB_test",
				"invite t3_userA_test t3_userD_test",
				"invite t3_userB_test t3_userC_test",
				"register t3_userA_test 123",
				"accept-invite t3_userC_test t3_userB_test",
				"list-friend t3_userA_test",
				"list-friend t3_userB_test",
				"list-friend t3_userC_test",
				"post t3_userA_test Hi I am A",
				"post t3_userB_test Hi I am B",
				"post t3_userC_test Hi I am C",
				"receive-post t3_userA_test",
				"receive-post t3_userB_test",
				"receive-post t3_userC_test",
				"logout t3_userD_test",
				"delete t3_userA_test",
				"delete t3_userB_test",
				"delete t3_userC_test",
			},
			[][]string{
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"No such user or password error"},
				{"Success!"},
				{"No such user or password error"},
				{"Not login yet"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"You cannot invite yourself"},
				{"Already invited"},
				{"t3_userA_test has invited you"},
				{"t3_userD_test does not exist"},
				{"t3_userB_test did not invite you"},
				{"Success!"},
				{"t3_userB_test is already your friend"},
				{"t3_userD_test does not exist"},
				{"Success!"},
				{"t3_userA_test is already used"},
				{"Success!"},
				{"t3_userB_test"},
				{"t3_userA_test", "t3_userC_test"},
				{"t3_userB_test"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"t3_userB_test: Hi I am B"},
				{"t3_userA_test: Hi I am A", "t3_userC_test: Hi I am C"},
				{"t3_userB_test: Hi I am B"},
				{"Not login yet"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
			},
		},
		{
			"Test4",
			[]string{
				"register t4_userA_test aaaaa",
				"register t4_userA_test bbbbb",
				"login t4_userA_test aaa",
				"register t4_userB_test aaaaa",
				"register t4_userC_test aaaaa",
				"login t4_userA_test aaaaa",
				"login t4_userC_test aaaaa",
				"invite t4_userB_test t4_userA_test",
				"invite t4_userA_test t4_userA_test",
				"invite t4_userA_test t4_userD_test",
				"invite t4_userA_test t4_userB_test",
				"invite t4_userA_test t4_userB_test",
				"invite t4_userC_test t4_userB_test",
				"logout t4_userA_test",
				"list-invite t4_userB_test",
				"login t4_userB_test aaaaa",
				"list-invite t4_userB_test",
				"accept-invite t4_userB_test t4_userA_test",
				"accept-invite t4_userC_test t4_userB_test",
				"invite t4_userB_test t4_userA_test",
				"invite t4_userB_test t4_userC_test",
				"list-invite t4_userB_test",
				"list-friend t4_userB_test",
				"post t4_userB_test wwwww",
				"login t4_userA_test aaaaa",
				"receive-post t4_userA_test",
				"accept-invite t4_userB_test t4_userC_test",
				"post t4_userC_test bello",
				"post t4_userA_test wow",
				"post t4_userA_test hahaha",
				"receive-post t4_userB_test",
				"delete t4_userC_test",
				"receive-post t4_userB_test",
				"delete t4_userB_test",
				"list-friend t4_userA_test",
				"delete t4_userA_test",
			},
			[][]string{
				{"Success!"},
				{"t4_userA_test is already used"},
				{"No such user or password error"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Not login yet"},
				{"You cannot invite yourself"},
				{"t4_userD_test does not exist"},
				{"Success!"},
				{"Already invited"},
				{"Success!"},
				{"Bye!"},
				{"Not login yet"},
				{"Success!"},
				{"t4_userA_test", "t4_userC_test"},
				{"Success!"},
				{"t4_userB_test did not invite you"},
				{"t4_userA_test is already your friend"},
				{"t4_userC_test has invited you"},
				{"t4_userC_test"},
				{"t4_userA_test"},
				{"Success!"},
				{"Success!"},
				{"t4_userB_test: wwwww"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"t4_userA_test: wow", "t4_userA_test: hahaha", "t4_userC_test: bello"},
				{"Success!"},
				{"t4_userA_test: wow", "t4_userA_test: hahaha"},
				{"Success!"},
				{"No friends"},
				{"Success!"},
			},
		},
		{
			"Test5",
			[]string{
				"asdf",
				"register t5_userA_test 123",
				"register t5_userB_test 456",
				"login t5_userA_test 456",
				"register t5_userC_test 741",
				"delete t5_userA_test",
				"login t5_userA_test 123",
				"login t5_userB_test 456",
				"delete t5_userA_test",
				"delete t5_userA_test",
				"login t5_userC_test 741",
				"logout t5_userB_test",
				"logout t5_userB_test",
				"invite t5_userB_test t5_userC_test",
				"invite t5_userC_test t5_userA_test",
				"register t5_userA_test 123",
				"invite t5_userC_test t5_userA_test",
				"login t5_userA_test 123",
				"login t5_userB_test 456",
				"accept-invite t5_userA_test t5_userC_test",
				"accept-invite t5_userB_test t5_userC_test",
				"invite t5_userC_test t5_userC_test",
				"list-invite t5_userC_test",
				"list-friend t5_userC_test",
				"invite t5_userA_test t5_userB_test",
				"list-invite t5_userB_test",
				"accept-invite t5_userA_test t5_userB_test",
				"post t5_userC_test hi everyone",
				"receive-post t5_userB_test",
				"delete t5_userA_test",
				"delete t5_userB_test",
				"delete t5_userC_test",
			},
			[][]string{
				{"Unknown command asdf"},
				{"Success!"},
				{"Success!"},
				{"No such user or password error"},
				{"Success!"},
				{"Not login yet"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Not login yet"},
				{"Success!"},
				{"Bye!"},
				{"Not login yet"},
				{"Not login yet"},
				{"t5_userA_test does not exist"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"t5_userC_test did not invite you"},
				{"You cannot invite yourself"},
				{"No invitations"},
				{"t5_userA_test"},
				{"Success!"},
				{"t5_userA_test"},
				{"t5_userB_test did not invite you"},
				{"Success!"},
				{"No posts"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
			},
		},
		{
			"Test6",
			[]string{
				"register t6_userA_test",
				"login t6_userA_test",
				"register t6_userA_test aaa",
				"login t6_userA_test aaa",
				"delete t6_userA_test t6_userB_test",
				"invite t6_userA_test t6_userB_test t6_userC_test",
				"list-invite t6_userA_test aaaaaa",
				"accept-invite t6_userA_test t6_userB_test t6_userB_test t6_userC_test",
				"list-friend t6_userA_test t6_userA_test",
				"post t6_userA_test",
				"receive-post t6_userA_test t6_userB_test",
				"logout t6_userA_test aaaaa",
				"del t6_userA_test",
				"delete t6_userA_test",
			},
			[][]string{
				{"Usage: register <id> <password>"},
				{"Usage: login <id> <password>"},
				{"Success!"},
				{"Success!"},
				{"Usage: delete <user>"},
				{"Usage: invite <user> <id>"},
				{"Usage: list-invite <user>"},
				{"Usage: accept-invite <user> <id>"},
				{"Usage: list-friend <user>"},
				{"Usage: post <user> <message>"},
				{"Usage: receive-post <user>"},
				{"Usage: logout <user>"},
				{"Unknown command del"},
				{"Success!"},
			},
		},
		{
			"Exit",
			[]string{
				"register test_exit test_exit",
				"login test_exit test_exit",
				"receive-post test_exit",
			},
			[][]string{
				{"Success!"},
				{"Success!"},
				{"No posts"},
			},
		},
		{
			"Exit_cont",
			[]string{
				"receive-post test_exit",
				"login test_exit test_exit",
				"delete test_exit",
			},
			[][]string{
				{"Not login yet"},
				{"Success!"},
				{"Success!"},
			},
		},
		{
			"Multiuser",
			[]string{
				"register multi1 1",
				"register multi2 2",
				"register multi3 3",
				"register multi4 4",
				"register multi5 5",
				"register multi6 6",
				"register multi7 7",
				"register multi8 8",
				"register multi9 9",
				"register multi10 10",
				"login multi1 1",
				"login multi2 2",
				"login multi3 3",
				"login multi4 4",
				"login multi5 5",
				"login multi6 6",
				"login multi7 7",
				"login multi8 8",
				"login multi9 9",
				"login multi10 10",
				"invite multi1 multi2",
				"invite multi2 multi3",
				"invite multi3 multi4",
				"invite multi4 multi5",
				"invite multi5 multi6",
				"invite multi6 multi7",
				"invite multi7 multi8",
				"invite multi8 multi9",
				"invite multi9 multi10",
				"invite multi10 multi1",
				"accept-invite multi10 multi9",
				"accept-invite multi9 multi8",
				"accept-invite multi8 multi7",
				"accept-invite multi7 multi6",
				"accept-invite multi6 multi5",
				"accept-invite multi5 multi4",
				"accept-invite multi4 multi3",
				"accept-invite multi3 multi2",
				"accept-invite multi2 multi1",
				"accept-invite multi1 multi10",
				"list-friend multi1",
				"list-friend multi2",
				"list-friend multi3",
				"list-friend multi4",
				"list-friend multi5",
				"list-friend multi6",
				"list-friend multi7",
				"list-friend multi8",
				"list-friend multi9",
				"list-friend multi10",
				"delete multi1",
				"delete multi2",
				"delete multi3",
				"delete multi4",
				"delete multi5",
				"delete multi6",
				"delete multi7",
				"delete multi8",
				"delete multi9",
				"delete multi10",
			},
			[][]string{
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"multi2", "multi10"},
				{"multi3", "multi1"},
				{"multi4", "multi2"},
				{"multi5", "multi3"},
				{"multi6", "multi4"},
				{"multi7", "multi5"},
				{"multi8", "multi6"},
				{"multi9", "multi7"},
				{"multi10", "multi8"},
				{"multi1", "multi9"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
			},
		},
	}

	beforeTest(t)
	doTest(t, testlist)
	afterTest(t)
}

func TestHW3(t *testing.T) {
	// Arrange
	testlist := []testcase{
		{
			"Test1",
			[]string{
				"register DeMo_user1 DeMo_pwd1 a",
				"register DeMo_user1 DeMo_pwd1",
				"register DeMo_user1 abc",
				"register DeMo_user2 DeMo_pwd2",
				"register DeMo_user2 abc",
				"register DeMo_user3 DeMo_pwd3",
				"register DeMo_user3 abc",
				"register DeMo_user4 DeMo_pwd4",
				"register DeMo_user4 abc",
				"register DeMo_user5 DeMo_pwd5",
				"register DeMo_user5 abc",
				"register DeMo_user6 DeMo_pwd6",
				"register DeMo_user6 abc",
				"register DeMo_user7 DeMo_pwd7",
				"register DeMo_user7 abc",
				"register DeMo_user8 DeMo_pwd8",
				"register DeMo_user8 abc",
				"register DeMo_user9 DeMo_pwd9",
				"register DeMo_user9 abc",
				"register DeMo_user10 DeMo_pwd10",
				"register DeMo_user10 abc",
				"register",
				"register a",
				"register a b c",
			},
			[][]string{
				{"Usage: register <id> <password>"},
				{"Success!"},
				{"DeMo_user1 is already used"},
				{"Success!"},
				{"DeMo_user2 is already used"},
				{"Success!"},
				{"DeMo_user3 is already used"},
				{"Success!"},
				{"DeMo_user4 is already used"},
				{"Success!"},
				{"DeMo_user5 is already used"},
				{"Success!"},
				{"DeMo_user6 is already used"},
				{"Success!"},
				{"DeMo_user7 is already used"},
				{"Success!"},
				{"DeMo_user8 is already used"},
				{"Success!"},
				{"DeMo_user9 is already used"},
				{"Success!"},
				{"DeMo_user10 is already used"},
				{"Usage: register <id> <password>"},
				{"Usage: register <id> <password>"},
				{"Usage: register <id> <password>"},
			},
		},
		{
			"Test2",
			[]string{
				"login DeMo_user1 DeMo_pwd1 a",
				"login DeMo_user1 DeMo_pwd1",
				"login DeMo_user2 DeMo_pwd2",
				"login DeMo_user3 DeMo_pwd3",
				"login DeMo_user4 DeMo_pwd4",
				"login DeMo_user5 DeMo_pwd5",
				"login DeMo_user6 DeMo_pwd6",
				"login DeMo_user7 DeMo_pwd7",
				"login DeMo_user8 DeMo_pwd8",
				"login DeMo_user9 DeMo_pwd9",
				"login DeMo_user10 DeMo_pwd10",
				"login DeMo_user1 DeMo_pwd1",
				"login DeMo_user2 DeMo_pwd2",
				"login DeMo_user3 DeMo_pwd3",
				"login DeMo_user4 DeMo_pwd4",
				"login DeMo_user5 DeMo_pwd5",
				"login DeMo_user6 DeMo_pwd6",
				"login DeMo_user7 DeMo_pwd7",
				"login DeMo_user8 DeMo_pwd8",
				"login DeMo_user9 DeMo_pwd9",
				"login DeMo_user10 DeMo_pwd10",
				"login",
				"login a",
				"login a b",
				"login a b c",
			},
			[][]string{
				{"Usage: login <id> <password>"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Usage: login <id> <password>"},
				{"Usage: login <id> <password>"},
				{"No such user or password error"},
				{"Usage: login <id> <password>"},
			},
		},
		{
			"Test3",
			[]string{
				"login DeMo_user1 DeMo_pwd1",
				"login DeMo_user2 DeMo_pwd2",
				"login DeMo_user3 DeMo_pwd3",
				"login DeMo_user4 DeMo_pwd4",
				"login DeMo_user5 DeMo_pwd5",
				"login DeMo_user6 DeMo_pwd6",
				"login DeMo_user7 DeMo_pwd7",
				"login DeMo_user8 DeMo_pwd8",
				"login DeMo_user9 DeMo_pwd9",
				"login DeMo_user10 DeMo_pwd10",
				"delete DeMo_user1 a",
				"delete DeMo_user1",
				"delete DeMo_user2",
				"delete DeMo_user3",
				"delete DeMo_user4",
				"delete DeMo_user5",
				"delete DeMo_user6",
				"delete DeMo_user7",
				"delete DeMo_user8",
				"delete DeMo_user9",
				"delete DeMo_user10",
				"delete DeMo_user1",
				"delete DeMo_user2",
				"delete DeMo_user3",
				"delete DeMo_user4",
				"delete DeMo_user5",
				"delete DeMo_user6",
				"delete DeMo_user7",
				"delete DeMo_user8",
				"delete DeMo_user9",
				"delete DeMo_user10",
				"login DeMo_user1 DeMo_pwd1",
				"login DeMo_user2 DeMo_pwd2",
				"login DeMo_user3 DeMo_pwd3",
				"login DeMo_user4 DeMo_pwd4",
				"login DeMo_user5 DeMo_pwd5",
				"login DeMo_user6 DeMo_pwd6",
				"login DeMo_user7 DeMo_pwd7",
				"login DeMo_user8 DeMo_pwd8",
				"login DeMo_user9 DeMo_pwd9",
				"login DeMo_user10 DeMo_pwd10",
				"delete",
				"delete a",
				"delete a b",
			},
			[][]string{
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Usage: delete <user>"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Not login yet"},
				{"Not login yet"},
				{"Not login yet"},
				{"Not login yet"},
				{"Not login yet"},
				{"Not login yet"},
				{"Not login yet"},
				{"Not login yet"},
				{"Not login yet"},
				{"Not login yet"},
				{"No such user or password error"},
				{"No such user or password error"},
				{"No such user or password error"},
				{"No such user or password error"},
				{"No such user or password error"},
				{"No such user or password error"},
				{"No such user or password error"},
				{"No such user or password error"},
				{"No such user or password error"},
				{"No such user or password error"},
				{"Not login yet"},
				{"Not login yet"},
				{"Not login yet"},
			},
		},
		{
			"Test4",
			[]string{
				"register DeMo_user1 DeMo_pwd1",
				"register DeMo_user2 DeMo_pwd2",
				"register DeMo_user3 DeMo_pwd3",
				"register DeMo_user4 DeMo_pwd4",
				"register DeMo_user5 DeMo_pwd5",
				"register DeMo_user6 DeMo_pwd6",
				"register DeMo_user7 DeMo_pwd7",
				"register DeMo_user8 DeMo_pwd8",
				"register DeMo_user9 DeMo_pwd9",
				"register DeMo_user10 DeMo_pwd10",
				"login DeMo_user1 DeMo_pwd1",
				"login DeMo_user2 DeMo_pwd2",
				"login DeMo_user3 DeMo_pwd3",
				"login DeMo_user4 DeMo_pwd4",
				"login DeMo_user5 DeMo_pwd5",
				"login DeMo_user6 DeMo_pwd6",
				"login DeMo_user7 DeMo_pwd7",
				"login DeMo_user8 DeMo_pwd8",
				"login DeMo_user9 DeMo_pwd9",
				"login DeMo_user10 DeMo_pwd10",
				"logout DeMo_user1 a",
				"logout DeMo_user1",
				"logout DeMo_user2",
				"logout DeMo_user3",
				"logout DeMo_user4",
				"logout DeMo_user5",
				"logout DeMo_user6",
				"logout DeMo_user7",
				"logout DeMo_user8",
				"logout DeMo_user9",
				"logout DeMo_user10",
				"logout DeMo_user1",
				"logout DeMo_user2",
				"logout DeMo_user3",
				"logout DeMo_user4",
				"logout DeMo_user5",
				"logout DeMo_user6",
				"logout DeMo_user7",
				"logout DeMo_user8",
				"logout DeMo_user9",
				"logout DeMo_user10",
				"login DeMo_user1 DeMo",
				"login DeMo_user2 DeMo",
				"login DeMo_user3 DeMo",
				"login DeMo_user4 DeMo",
				"login DeMo_user5 DeMo",
				"login DeMo_user6 DeMo",
				"login DeMo_user7 DeMo",
				"login DeMo_user8 DeMo",
				"login DeMo_user9 DeMo",
				"login DeMo_user10 DeMo",
				"login DeMo_user1 DeMo_pwd1",
				"login DeMo_user2 DeMo_pwd2",
				"login DeMo_user3 DeMo_pwd3",
				"login DeMo_user4 DeMo_pwd4",
				"login DeMo_user5 DeMo_pwd5",
				"login DeMo_user6 DeMo_pwd6",
				"login DeMo_user7 DeMo_pwd7",
				"login DeMo_user8 DeMo_pwd8",
				"login DeMo_user9 DeMo_pwd9",
				"login DeMo_user10 DeMo_pwd10",
				"logout",
				"logout a",
				"logout a b",
			},
			[][]string{
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Usage: logout <user>"},
				{"Bye!"},
				{"Bye!"},
				{"Bye!"},
				{"Bye!"},
				{"Bye!"},
				{"Bye!"},
				{"Bye!"},
				{"Bye!"},
				{"Bye!"},
				{"Bye!"},
				{"Not login yet"},
				{"Not login yet"},
				{"Not login yet"},
				{"Not login yet"},
				{"Not login yet"},
				{"Not login yet"},
				{"Not login yet"},
				{"Not login yet"},
				{"Not login yet"},
				{"Not login yet"},
				{"No such user or password error"},
				{"No such user or password error"},
				{"No such user or password error"},
				{"No such user or password error"},
				{"No such user or password error"},
				{"No such user or password error"},
				{"No such user or password error"},
				{"No such user or password error"},
				{"No such user or password error"},
				{"No such user or password error"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Not login yet"},
				{"Not login yet"},
				{"Not login yet"},
			},
		},
		{
			"Test5",
			[]string{
				"login DeMo_user1 DeMo_pwd1",
				"login DeMo_user2 DeMo_pwd2",
				"login DeMo_user3 DeMo_pwd3",
				"login DeMo_user4 DeMo_pwd4",
				"login DeMo_user5 DeMo_pwd5",
				"login DeMo_user6 DeMo_pwd6",
				"login DeMo_user7 DeMo_pwd7",
				"login DeMo_user8 DeMo_pwd8",
				"login DeMo_user9 DeMo_pwd9",
				"login DeMo_user10 DeMo_pwd10",
				"invite DeMo_user1 FAKE_USER",
				"invite DeMo_user1 DeMo_user2 a",
				"invite DeMo_user1 DeMo_user2",
				"invite DeMo_user2 DeMo_user3",
				"invite DeMo_user3 DeMo_user5",
				"invite DeMo_user5 DeMo_user7",
				"invite DeMo_user7 DeMo_user8",
				"invite DeMo_user8 DeMo_user9",
				"invite DeMo_user9 DeMo_user10",
				"invite DeMo_user10 DeMo_user1",
				"invite DeMo_user1 DeMo_user1",
				"invite DeMo_user2 DeMo_user1",
				"invite DeMo_user1 DeMo_user2",
				"invite DeMo_user2 DeMo_user3",
				"invite DeMo_user3 DeMo_user5",
				"invite DeMo_user5 DeMo_user7",
				"invite DeMo_user7 DeMo_user8",
				"invite DeMo_user8 DeMo_user9",
				"invite DeMo_user9 DeMo_user10",
				"invite DeMo_user10 DeMo_user1",
				"invite",
				"invite a",
				"invite a b",
				"invite a b c",
			},
			[][]string{
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"FAKE_USER does not exist"},
				{"Usage: invite <user> <id>"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"You cannot invite yourself"},
				{"DeMo_user1 has invited you"},
				{"Already invited"},
				{"Already invited"},
				{"Already invited"},
				{"Already invited"},
				{"Already invited"},
				{"Already invited"},
				{"Already invited"},
				{"Already invited"},
				{"Not login yet"},
				{"Not login yet"},
				{"Not login yet"},
				{"Not login yet"},
			},
		},
		{
			"Test6",
			[]string{
				"login DeMo_user1 DeMo_pwd1",
				"login DeMo_user2 DeMo_pwd2",
				"login DeMo_user3 DeMo_pwd3",
				"login DeMo_user4 DeMo_pwd4",
				"login DeMo_user5 DeMo_pwd5",
				"login DeMo_user6 DeMo_pwd6",
				"login DeMo_user7 DeMo_pwd7",
				"login DeMo_user8 DeMo_pwd8",
				"login DeMo_user9 DeMo_pwd9",
				"login DeMo_user10 DeMo_pwd10",
				"list-invite DeMo_user1 a",
				"list-invite DeMo_user1",
				"login DeMo_user1 DeMo_pwd1",
				"list-invite DeMo_user2",
				"login DeMo_user1 DeMo_pwd1",
				"list-invite DeMo_user3",
				"login DeMo_user1 DeMo_pwd1",
				"list-invite DeMo_user4",
				"login DeMo_user1 DeMo_pwd1",
				"list-invite DeMo_user5",
				"login DeMo_user1 DeMo_pwd1",
				"list-invite DeMo_user6",
				"login DeMo_user1 DeMo_pwd1",
				"list-invite DeMo_user7",
				"login DeMo_user1 DeMo_pwd1",
				"list-invite DeMo_user8",
				"login DeMo_user1 DeMo_pwd1",
				"list-invite DeMo_user9",
				"login DeMo_user1 DeMo_pwd1",
				"list-invite DeMo_user10",
				"login DeMo_user1 DeMo_pwd1",
				"list-invite DeMo_user10",
				"login DeMo_user1 DeMo_pwd1",
				"list-invite DeMo_user9",
				"login DeMo_user1 DeMo_pwd1",
				"list-invite DeMo_user8",
				"login DeMo_user1 DeMo_pwd1",
				"list-invite DeMo_user7",
				"login DeMo_user1 DeMo_pwd1",
				"list-invite DeMo_user6",
				"login DeMo_user1 DeMo_pwd1",
				"list-invite DeMo_user5",
				"login DeMo_user1 DeMo_pwd1",
				"list-invite DeMo_user4",
				"login DeMo_user1 DeMo_pwd1",
				"list-invite DeMo_user3",
				"login DeMo_user1 DeMo_pwd1",
				"list-invite DeMo_user2",
				"login DeMo_user1 DeMo_pwd1",
				"list-invite DeMo_user1",
				"list-invite",
				"list-invite a",
				"list-invite a b",
			},
			[][]string{
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Usage: list-invite <user>"},
				{"DeMo_user10"},
				{"Success!"},
				{"DeMo_user1"},
				{"Success!"},
				{"DeMo_user2"},
				{"Success!"},
				{"No invitations"},
				{"Success!"},
				{"DeMo_user3"},
				{"Success!"},
				{"No invitations"},
				{"Success!"},
				{"DeMo_user5"},
				{"Success!"},
				{"DeMo_user7"},
				{"Success!"},
				{"DeMo_user8"},
				{"Success!"},
				{"DeMo_user9"},
				{"Success!"},
				{"DeMo_user9"},
				{"Success!"},
				{"DeMo_user8"},
				{"Success!"},
				{"DeMo_user7"},
				{"Success!"},
				{"DeMo_user5"},
				{"Success!"},
				{"No invitations"},
				{"Success!"},
				{"DeMo_user3"},
				{"Success!"},
				{"No invitations"},
				{"Success!"},
				{"DeMo_user2"},
				{"Success!"},
				{"DeMo_user1"},
				{"Success!"},
				{"DeMo_user10"},
				{"Not login yet"},
				{"Not login yet"},
				{"Not login yet"},
			},
		},
		{
			"Test7",
			[]string{
				"login DeMo_user1 DeMo_pwd1",
				"login DeMo_user2 DeMo_pwd2",
				"login DeMo_user3 DeMo_pwd3",
				"login DeMo_user4 DeMo_pwd4",
				"login DeMo_user5 DeMo_pwd5",
				"login DeMo_user6 DeMo_pwd6",
				"login DeMo_user7 DeMo_pwd7",
				"login DeMo_user8 DeMo_pwd8",
				"login DeMo_user9 DeMo_pwd9",
				"login DeMo_user10 DeMo_pwd10",
				"accept-invite DeMo_user1",
				"accept-invite DeMo_user1 a",
				"accept-invite DeMo_user1 DeMo_user10",
				"accept-invite DeMo_user2 DeMo_user1",
				"accept-invite DeMo_user3 DeMo_user2",
				"accept-invite DeMo_user4 DeMo_user3",
				"accept-invite DeMo_user5 DeMo_user4",
				"accept-invite DeMo_user6 DeMo_user5",
				"accept-invite DeMo_user7 DeMo_user6",
				"accept-invite DeMo_user8 DeMo_user7",
				"accept-invite DeMo_user9 DeMo_user8",
				"accept-invite DeMo_user10 DeMo_user9",
				"accept-invite DeMo_user1 DeMo_user10",
				"accept-invite DeMo_user2 DeMo_user1",
				"accept-invite DeMo_user3 DeMo_user2",
				"accept-invite DeMo_user4 DeMo_user3",
				"accept-invite DeMo_user5 DeMo_user4",
				"accept-invite DeMo_user6 DeMo_user5",
				"accept-invite DeMo_user7 DeMo_user6",
				"accept-invite DeMo_user8 DeMo_user7",
				"accept-invite DeMo_user9 DeMo_user8",
				"accept-invite DeMo_user10 DeMo_user9",
				"invite DeMo_user1 DeMo_user2",
				"invite DeMo_user2 DeMo_user3",
				"invite DeMo_user3 DeMo_user5",
				"invite DeMo_user5 DeMo_user7",
				"invite DeMo_user7 DeMo_user8",
				"invite DeMo_user8 DeMo_user9",
				"invite DeMo_user9 DeMo_user10",
				"list-invite DeMo_user1",
				"list-invite DeMo_user2",
				"list-invite DeMo_user3",
				"list-invite DeMo_user4",
				"list-invite DeMo_user5",
				"list-invite DeMo_user6",
				"list-invite DeMo_user7",
				"list-invite DeMo_user8",
				"list-invite DeMo_user9",
				"list-invite DeMo_user10",
				"accept-invite",
				"accept-invite a",
				"accept-invite a b",
				"accept-invite a b c",
			},
			[][]string{
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Usage: accept-invite <user> <id>"},
				{"a did not invite you"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"DeMo_user3 did not invite you"},
				{"DeMo_user4 did not invite you"},
				{"DeMo_user5 did not invite you"},
				{"DeMo_user6 did not invite you"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"DeMo_user10 did not invite you"},
				{"DeMo_user1 did not invite you"},
				{"DeMo_user2 did not invite you"},
				{"DeMo_user3 did not invite you"},
				{"DeMo_user4 did not invite you"},
				{"DeMo_user5 did not invite you"},
				{"DeMo_user6 did not invite you"},
				{"DeMo_user7 did not invite you"},
				{"DeMo_user8 did not invite you"},
				{"DeMo_user9 did not invite you"},
				{"DeMo_user2 is already your friend"},
				{"DeMo_user3 is already your friend"},
				{"Already invited"},
				{"Already invited"},
				{"DeMo_user8 is already your friend"},
				{"DeMo_user9 is already your friend"},
				{"DeMo_user10 is already your friend"},
				{"No invitations"},
				{"No invitations"},
				{"No invitations"},
				{"No invitations"},
				{"DeMo_user3"},
				{"No invitations"},
				{"DeMo_user5"},
				{"No invitations"},
				{"No invitations"},
				{"No invitations"},
				{"Not login yet"},
				{"Not login yet"},
				{"Not login yet"},
				{"Not login yet"},
			},
		},
		{
			"Test8",
			[]string{
				"login DeMo_user1 DeMo_pwd1",
				"login DeMo_user2 DeMo_pwd2",
				"login DeMo_user3 DeMo_pwd3",
				"login DeMo_user4 DeMo_pwd4",
				"login DeMo_user5 DeMo_pwd5",
				"login DeMo_user6 DeMo_pwd6",
				"login DeMo_user7 DeMo_pwd7",
				"login DeMo_user8 DeMo_pwd8",
				"login DeMo_user9 DeMo_pwd9",
				"login DeMo_user10 DeMo_pwd10",
				"list-friend DeMo_user1 a",
				"list-friend DeMo_user1",
				"login DeMo_user1 DeMo_pwd1",
				"list-friend DeMo_user2",
				"login DeMo_user1 DeMo_pwd1",
				"list-friend DeMo_user3",
				"login DeMo_user1 DeMo_pwd1",
				"list-friend DeMo_user4",
				"login DeMo_user1 DeMo_pwd1",
				"list-friend DeMo_user5",
				"login DeMo_user1 DeMo_pwd1",
				"list-friend DeMo_user6",
				"login DeMo_user1 DeMo_pwd1",
				"list-friend DeMo_user7",
				"login DeMo_user1 DeMo_pwd1",
				"list-friend DeMo_user8",
				"login DeMo_user1 DeMo_pwd1",
				"list-friend DeMo_user9",
				"login DeMo_user1 DeMo_pwd1",
				"list-friend DeMo_user10",
				"login DeMo_user1 DeMo_pwd1",
				"list-friend DeMo_user10",
				"login DeMo_user1 DeMo_pwd1",
				"list-friend DeMo_user9",
				"login DeMo_user1 DeMo_pwd1",
				"list-friend DeMo_user8",
				"login DeMo_user1 DeMo_pwd1",
				"list-friend DeMo_user7",
				"login DeMo_user1 DeMo_pwd1",
				"list-friend DeMo_user6",
				"login DeMo_user1 DeMo_pwd1",
				"list-friend DeMo_user5",
				"login DeMo_user1 DeMo_pwd1",
				"list-friend DeMo_user4",
				"login DeMo_user1 DeMo_pwd1",
				"list-friend DeMo_user3",
				"login DeMo_user1 DeMo_pwd1",
				"list-friend DeMo_user2",
				"login DeMo_user1 DeMo_pwd1",
				"list-friend DeMo_user1",
				"list-friend",
				"list-friend a",
				"list-friend a b",
			},
			[][]string{
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Usage: list-friend <user>"},
				{"DeMo_user10", "DeMo_user2"},
				{"Success!"},
				{"DeMo_user1", "DeMo_user3"},
				{"Success!"},
				{"DeMo_user2"},
				{"Success!"},
				{"No friends"},
				{"Success!"},
				{"No friends"},
				{"Success!"},
				{"No friends"},
				{"Success!"},
				{"DeMo_user8"},
				{"Success!"},
				{"DeMo_user7", "DeMo_user9"},
				{"Success!"},
				{"DeMo_user8", "DeMo_user10"},
				{"Success!"},
				{"DeMo_user9", "DeMo_user1"},
				{"Success!"},
				{"DeMo_user9", "DeMo_user1"},
				{"Success!"},
				{"DeMo_user8", "DeMo_user10"},
				{"Success!"},
				{"DeMo_user7", "DeMo_user9"},
				{"Success!"},
				{"DeMo_user8"},
				{"Success!"},
				{"No friends"},
				{"Success!"},
				{"No friends"},
				{"Success!"},
				{"No friends"},
				{"Success!"},
				{"DeMo_user2"},
				{"Success!"},
				{"DeMo_user1", "DeMo_user3"},
				{"Success!"},
				{"DeMo_user10", "DeMo_user2"},
				{"Not login yet"},
				{"Not login yet"},
				{"Not login yet"},
			},
		},
		{
			"Test9",
			[]string{
				"login DeMo_user1 DeMo_pwd1",
				"login DeMo_user2 DeMo_pwd2",
				"login DeMo_user3 DeMo_pwd3",
				"login DeMo_user4 DeMo_pwd4",
				"login DeMo_user5 DeMo_pwd5",
				"login DeMo_user6 DeMo_pwd6",
				"login DeMo_user7 DeMo_pwd7",
				"login DeMo_user8 DeMo_pwd8",
				"login DeMo_user9 DeMo_pwd9",
				"login DeMo_user10 DeMo_pwd10",
				"post DeMo_user1",
				"post DeMo_user1 HI, I AM USER1.",
				"post DeMo_user2 HI, I AM USER2.",
				"post DeMo_user3 HI, I AM USER3.",
				"post DeMo_user4 HI, I AM USER4.",
				"post DeMo_user5 HI, I AM USER5.",
				"post DeMo_user6 HI, I AM USER6.",
				"post DeMo_user7 HI, I AM USER7.",
				"post DeMo_user8 HI, I AM USER8.",
				"post DeMo_user9 HI, I AM USER9.",
				"post DeMo_user10 HI, I AM USER10.",
				"post DeMo_user1 WELCOME TO HAPPY PROJECT 3! USER10, USER2",
				"post DeMo_user2 WELCOME TO HAPPY PROJECT 3! USER1, USER3",
				"post DeMo_user3 WELCOME TO HAPPY PROJECT 3! USER2, USER4",
				"post DeMo_user4 WELCOME TO HAPPY PROJECT 3! USER3, USER5",
				"post DeMo_user5 WELCOME TO HAPPY PROJECT 3! USER4, USER6",
				"post DeMo_user6 WELCOME TO HAPPY PROJECT 3! USER5, USER7",
				"post DeMo_user7 WELCOME TO HAPPY PROJECT 3! USER6, USER8",
				"post DeMo_user8 WELCOME TO HAPPY PROJECT 3! USER7, USER9",
				"post DeMo_user9 WELCOME TO HAPPY PROJECT 3! USER8, USER10",
				"post DeMo_user10 WELCOME TO HAPPY PROJECT 3! USER9, USER1",
				"post",
				"post a",
				"post a b",
				"post a b c",
			},
			[][]string{
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Usage: post <user> <message>"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Not login yet"},
				{"Not login yet"},
				{"Not login yet"},
				{"Not login yet"},
			},
		},
		{
			"Test10",
			[]string{
				"login DeMo_user1 DeMo_pwd1",
				"login DeMo_user2 DeMo_pwd2",
				"login DeMo_user3 DeMo_pwd3",
				"login DeMo_user4 DeMo_pwd4",
				"login DeMo_user5 DeMo_pwd5",
				"login DeMo_user6 DeMo_pwd6",
				"login DeMo_user7 DeMo_pwd7",
				"login DeMo_user8 DeMo_pwd8",
				"login DeMo_user9 DeMo_pwd9",
				"login DeMo_user10 DeMo_pwd10",
				"receive-post DeMo_user1 a",
				"receive-post DeMo_user1",
				"login DeMo_user1 DeMo_pwd1",
				"receive-post DeMo_user2",
				"login DeMo_user1 DeMo_pwd1",
				"receive-post DeMo_user3",
				"login DeMo_user1 DeMo_pwd1",
				"receive-post DeMo_user4",
				"login DeMo_user1 DeMo_pwd1",
				"receive-post DeMo_user5",
				"login DeMo_user1 DeMo_pwd1",
				"receive-post DeMo_user6",
				"login DeMo_user1 DeMo_pwd1",
				"receive-post DeMo_user7",
				"login DeMo_user1 DeMo_pwd1",
				"receive-post DeMo_user8",
				"login DeMo_user1 DeMo_pwd1",
				"receive-post DeMo_user9",
				"login DeMo_user1 DeMo_pwd1",
				"receive-post DeMo_user10",
				"login DeMo_user1 DeMo_pwd1",
				"receive-post DeMo_user1",
				"login DeMo_user1 DeMo_pwd1",
				"receive-post DeMo_user2",
				"login DeMo_user1 DeMo_pwd1",
				"receive-post DeMo_user3",
				"login DeMo_user1 DeMo_pwd1",
				"receive-post DeMo_user4",
				"login DeMo_user1 DeMo_pwd1",
				"receive-post DeMo_user5",
				"login DeMo_user1 DeMo_pwd1",
				"receive-post DeMo_user6",
				"login DeMo_user1 DeMo_pwd1",
				"receive-post DeMo_user7",
				"login DeMo_user1 DeMo_pwd1",
				"receive-post DeMo_user8",
				"login DeMo_user1 DeMo_pwd1",
				"receive-post DeMo_user9",
				"login DeMo_user1 DeMo_pwd1",
				"receive-post DeMo_user10",
				"login DeMo_user1 DeMo_pwd1",
				"receive-post DeMo_user10",
				"login DeMo_user1 DeMo_pwd1",
				"receive-post DeMo_user9",
				"login DeMo_user1 DeMo_pwd1",
				"receive-post DeMo_user8",
				"login DeMo_user1 DeMo_pwd1",
				"receive-post DeMo_user7",
				"login DeMo_user1 DeMo_pwd1",
				"receive-post DeMo_user6",
				"login DeMo_user1 DeMo_pwd1",
				"receive-post DeMo_user5",
				"login DeMo_user1 DeMo_pwd1",
				"receive-post DeMo_user4",
				"login DeMo_user1 DeMo_pwd1",
				"receive-post DeMo_user3",
				"login DeMo_user1 DeMo_pwd1",
				"receive-post DeMo_user2",
				"login DeMo_user1 DeMo_pwd1",
				"receive-post DeMo_user1",
				"receive-post",
				"receive-post a",
				"receive-post a b",
			},
			[][]string{
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Success!"},
				{"Usage: receive-post <user>"},
				{
					"DeMo_user10: HI, I AM USER10.",
					"DeMo_user10: WELCOME TO HAPPY PROJECT 3! USER9, USER1",
					"DeMo_user2: HI, I AM USER2.",
					"DeMo_user2: WELCOME TO HAPPY PROJECT 3! USER1, USER3",
				},
				{"Success!"},
				{
					"DeMo_user1: HI, I AM USER1.",
					"DeMo_user1: WELCOME TO HAPPY PROJECT 3! USER10, USER2",
					"DeMo_user3: HI, I AM USER3.",
					"DeMo_user3: WELCOME TO HAPPY PROJECT 3! USER2, USER4",
				},
				{"Success!"},
				{
					"DeMo_user2: HI, I AM USER2.",
					"DeMo_user2: WELCOME TO HAPPY PROJECT 3! USER1, USER3",
				},
				{"Success!"},
				{"No posts"},
				{"Success!"},
				{"No posts"},
				{"Success!"},
				{"No posts"},
				{"Success!"},
				{
					"DeMo_user8: HI, I AM USER8.",
					"DeMo_user8: WELCOME TO HAPPY PROJECT 3! USER7, USER9",
				},
				{"Success!"},
				{
					"DeMo_user7: HI, I AM USER7.",
					"DeMo_user7: WELCOME TO HAPPY PROJECT 3! USER6, USER8",
					"DeMo_user9: HI, I AM USER9.",
					"DeMo_user9: WELCOME TO HAPPY PROJECT 3! USER8, USER10",
				},
				{"Success!"},
				{
					"DeMo_user8: HI, I AM USER8.",
					"DeMo_user8: WELCOME TO HAPPY PROJECT 3! USER7, USER9",
					"DeMo_user10: HI, I AM USER10.",
					"DeMo_user10: WELCOME TO HAPPY PROJECT 3! USER9, USER1",
				},
				{"Success!"},
				{
					"DeMo_user9: HI, I AM USER9.",
					"DeMo_user9: WELCOME TO HAPPY PROJECT 3! USER8, USER10",
					"DeMo_user1: HI, I AM USER1.",
					"DeMo_user1: WELCOME TO HAPPY PROJECT 3! USER10, USER2",
				},
				{"Success!"},
				{
					"DeMo_user10: HI, I AM USER10.",
					"DeMo_user10: WELCOME TO HAPPY PROJECT 3! USER9, USER1",
					"DeMo_user2: HI, I AM USER2.",
					"DeMo_user2: WELCOME TO HAPPY PROJECT 3! USER1, USER3",
				},
				{"Success!"},
				{
					"DeMo_user1: HI, I AM USER1.",
					"DeMo_user1: WELCOME TO HAPPY PROJECT 3! USER10, USER2",
					"DeMo_user3: HI, I AM USER3.",
					"DeMo_user3: WELCOME TO HAPPY PROJECT 3! USER2, USER4",
				},
				{"Success!"},
				{
					"DeMo_user2: HI, I AM USER2.",
					"DeMo_user2: WELCOME TO HAPPY PROJECT 3! USER1, USER3",
				},
				{"Success!"},
				{"No posts"},
				{"Success!"},
				{"No posts"},
				{"Success!"},
				{"No posts"},
				{"Success!"},
				{
					"DeMo_user8: HI, I AM USER8.",
					"DeMo_user8: WELCOME TO HAPPY PROJECT 3! USER7, USER9",
				},
				{"Success!"},
				{
					"DeMo_user7: HI, I AM USER7.",
					"DeMo_user7: WELCOME TO HAPPY PROJECT 3! USER6, USER8",
					"DeMo_user9: HI, I AM USER9.",
					"DeMo_user9: WELCOME TO HAPPY PROJECT 3! USER8, USER10",
				},
				{"Success!"},
				{
					"DeMo_user8: HI, I AM USER8.",
					"DeMo_user8: WELCOME TO HAPPY PROJECT 3! USER7, USER9",
					"DeMo_user10: HI, I AM USER10.",
					"DeMo_user10: WELCOME TO HAPPY PROJECT 3! USER9, USER1",
				},
				{"Success!"},
				{
					"DeMo_user9: HI, I AM USER9.",
					"DeMo_user9: WELCOME TO HAPPY PROJECT 3! USER8, USER10",
					"DeMo_user1: HI, I AM USER1.",
					"DeMo_user1: WELCOME TO HAPPY PROJECT 3! USER10, USER2",
				},
				{"Success!"},
				{
					"DeMo_user9: HI, I AM USER9.",
					"DeMo_user9: WELCOME TO HAPPY PROJECT 3! USER8, USER10",
					"DeMo_user1: HI, I AM USER1.",
					"DeMo_user1: WELCOME TO HAPPY PROJECT 3! USER10, USER2",
				},
				{"Success!"},
				{
					"DeMo_user8: HI, I AM USER8.",
					"DeMo_user8: WELCOME TO HAPPY PROJECT 3! USER7, USER9",
					"DeMo_user10: HI, I AM USER10.",
					"DeMo_user10: WELCOME TO HAPPY PROJECT 3! USER9, USER1",
				},
				{"Success!"},
				{
					"DeMo_user7: HI, I AM USER7.",
					"DeMo_user7: WELCOME TO HAPPY PROJECT 3! USER6, USER8",
					"DeMo_user9: HI, I AM USER9.",
					"DeMo_user9: WELCOME TO HAPPY PROJECT 3! USER8, USER10",
				},
				{"Success!"},
				{
					"DeMo_user8: HI, I AM USER8.",
					"DeMo_user8: WELCOME TO HAPPY PROJECT 3! USER7, USER9",
				},
				{"Success!"},
				{"No posts"},
				{"Success!"},
				{"No posts"},
				{"Success!"},
				{"No posts"},
				{"Success!"},
				{
					"DeMo_user2: HI, I AM USER2.",
					"DeMo_user2: WELCOME TO HAPPY PROJECT 3! USER1, USER3",
				},
				{"Success!"},
				{
					"DeMo_user1: HI, I AM USER1.",
					"DeMo_user1: WELCOME TO HAPPY PROJECT 3! USER10, USER2",
					"DeMo_user3: HI, I AM USER3.",
					"DeMo_user3: WELCOME TO HAPPY PROJECT 3! USER2, USER4",
				},
				{"Success!"},
				{
					"DeMo_user10: HI, I AM USER10.",
					"DeMo_user10: WELCOME TO HAPPY PROJECT 3! USER9, USER1",
					"DeMo_user2: HI, I AM USER2.",
					"DeMo_user2: WELCOME TO HAPPY PROJECT 3! USER1, USER3",
				},
				{"Not login yet"},
				{"Not login yet"},
				{"Not login yet"},
			},
		},
		{
			"Test11",
			[]string{
				"reg a a",
				"logi a a",
				"receive-p a",
				"list-i a",
				"list-f a",
				"pos a",
				"accept a",
				"inv a",
				"logo a",
				"del a",
				"exi",
			},
			[][]string{
				{"Unknown command reg"},
				{"Unknown command logi"},
				{"Unknown command receive-p"},
				{"Unknown command list-i"},
				{"Unknown command list-f"},
				{"Unknown command pos"},
				{"Unknown command accept"},
				{"Unknown command inv"},
				{"Unknown command logo"},
				{"Unknown command del"},
				{"Unknown command exi"},
			},
		},
	}

	beforeTest(t)
	doTest(t, testlist)
	afterTest(t)
}
